### ISSUE TITLE
Module not found: Error: Can't resolve 'stream/web'

### ISSUE THREAD

**Issue by ctq123** [node-fetch/fetch-blob#117] opened 2021-09-08 04:05 UTC
**Reproduction**

Module not found: Error: Can't resolve 'stream/web' in '/Users/alan/project/duapp/vscode/packages/du-i18n/node_modules/fetch-blob'

![image](https://user-images.githubusercontent.com/12124169/132444620-a3e22559-8ab3-4e07-9892-a15d99740d88.png)

1. yarn
2. yarn start
3. start fail

**Expected behavior**

start success

**Screenshots**

**Your Environment**
vscode extension development

| software         | version
| ---------------- | -------
| node-fetch       | 3.0.0
| node             | v14.17.3
| npm              | 6.14.13
| Operating System | macos

**Additional context**

**Comment by jimmywarting** [comment] 2021-09-08 06:59
don't get why u recive a error. it's wrapped around a try/catch

**Comment by LinusU** [comment] 2021-09-08 18:24
@ctq123 I believe that this is only a warning right? When WebPack detects an import inside `try`/`catch` it just prints a warning, the bundle should still be okay to use...

**Comment by btakita** [comment] 2021-09-10 21:20
Running sapper, rollup, on AWS Lambda with version nodejs14.x.

I'm getting the error:

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from /home/brian/work/menus/menus-angular-2-app/apps/web/server2.js
    at packageResolve (internal/modules/esm/resolve.js:664:9)
    at moduleResolve (internal/modules/esm/resolve.js:705:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by jimmywarting** [comment] 2021-09-11 20:50
Hmm, i did not account for bundlers to hoist stuff like this. This kind of conditional import should really be converted to top level await + async import to match the same behavior...

**Comment by wood1986** [comment] 2021-09-12 05:03
webpack should add `stream/web` to `NodeTargetPlugin`

**Comment by jimmywarting** [comment] 2021-09-12 07:07
Would it not be better to flag everything that starts with "node:" prefix and everything including "stream/*" instead of adding every subpath?

**Comment by ctq123** [comment] 2021-09-15 06:04
> bundle should still be okay to use.

yes，it don't affect packaging, but it's not friendly to runtime

**Comment by dominikg** [comment] 2021-09-16 18:41
this issue prevents sveltekit from updating to node-fetch 3.0.0

I've tried looking into it yesterday and wonder about a couple of things:

1) you are not tagging node internal modules with `node:` which is recommended for esm.
Would tagging the internal modules make life easier for bundlers to detect new/unknown node internals? 

2) the package.json files of node-fetch and fetch-blob do not contain "exports" mapping or "module" fields
they may not be strictly required, but exporting package.json is a common courtesy and using exports is recommended here too https://github.com/sindresorhus/meta/discussions/15

3) fetch-blob uses require in `streams.cjs`. (to avoid using top level await for node12 support i guess)
Are there ways to avoid this direct require?
* https://nodejs.org/api/module.html#module_module_createrequire_filename
* use process.version to figure out if `node:streams/web` is available and lazily dynamic import the best available option on first use?
* ???
*

**Comment by jimmywarting** [comment] 2021-09-16 19:05
1. this old issue made me belive i targeted 12.17 https://github.com/node-fetch/fetch-blob/issues/98 but the node.engine is set to 12.20. so we should be okey to use `node:`
2. so far i have not had any problems with it with the way it's right now.
3. yes it's to avoid top-level await for 12.20 support... haven't come up with any better solution yet

> and lazily dynamic import 

dynamic import is challenging `const stream = new Blob().stream()` is all sync would be different if stream returned a promise...

i have tried to best come up with a solution that don't import/depend on core node stuff. so that require can gracefully fail in Deno and Browser
like this result: https://cdn.jsdelivr.net/npm/fetch-blob/+esm
but others produce stuff like: https://jspm.dev/fetch-blob that fails totally

**Comment by benmccann** [comment] 2021-09-22 04:21
Here's the problematic line for reference: https://github.com/node-fetch/fetch-blob/blob/46476faf498dec035ab91b5a2d0fccd279629bce/streams.cjs#L7

**Comment by benmccann** [comment] 2021-09-22 04:44
Would anyone be able to report this as a bug to Rollup that it's hoisting the import outside of the try / catch? I tried taking a look at it briefly, but wasn't able to reproduce in the REPL. I'm wondering if anyone has ideas for reproducing this for a bug report?

https://rollupjs.org/repl/?version=2.38.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmlmJTIwKCFnbG9iYWxUaGlzLlJlYWRhYmxlU3RyZWFtKSUyMCU3QiU1Q24lMjAlMjB0cnklMjAlN0IlNUNuJTIwJTIwJTIwJTIwT2JqZWN0LmFzc2lnbihnbG9iYWxUaGlzJTJDJTIwcmVxdWlyZSgnc3RyZWFtJTJGd2ViJykpJTVDbiUyMCUyMCU3RCUyMGNhdGNoJTIwKGVycm9yKSUyMCU3QiU1Q24lNUN0JTVDdCUyRiUyRiUyMFRPRE8lM0ElMjBSZW1vdmUlMjB3aGVuJTIwb25seSUyMHN1cHBvcnRpbmclMjBub2RlJTIwJTNFJTNEJTIwMTYuNS4wJTVDbiUyMCUyMCUyMCUyME9iamVjdC5hc3NpZ24oZ2xvYmFsVGhpcyUyQyUyMHJlcXVpcmUoJ3dlYi1zdHJlYW1zLXBvbHlmaWxsJTJGZGlzdCUyRnBvbnlmaWxsLmVzMjAxOC5qcycpKSU1Q24lMjAlMjAlN0QlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by jimmywarting** [comment] 2021-09-22 08:48
> Would anyone be able to report this as a bug to Rollup that it's hoisting the import outside of the try / catch?

Kind of already did: https://github.com/rollup/rollup/issues/3621

**Comment by jimmywarting** [comment] 2021-09-22 08:52
> I'm wondering if anyone has ideas for reproducing this for a bug report?

It could also be someones else fault... I mean the file is in a `.cjs` extension. (cuz it's suppose to stay in cjs format) but for some reason it's being rewritten into `import require$$0 from 'stream/web';`

**Comment by benmccann** [comment] 2021-09-23 03:26
This looks like it could be related: https://github.com/rollup/plugins/tree/master/packages/commonjs#ignoretrycatch. Vite includes `@rollup/plugin-commonjs` by default. Though I tried setting it to `true` and it didn't seem to change anything

**Comment by benmccann** [comment] 2021-09-27 17:38
Actually, that option did fix the error for me. I just set it in the wrong place the first time around. Here's a working version: https://github.com/sveltejs/kit/pull/2422

I think the default value for this option should be changed in `@rollup/plugin-commonjs` to avoid this issue: https://github.com/rollup/plugins/issues/1004

**Comment by jimmywarting** [comment] 2021-09-27 19:08
Thank you @benmccann for finding the root cause

**Comment by xkn1ght** [comment] 2021-09-28 14:26
The 'stream/web' module is conditionally required, i.e. should be an optionalDependencies in the package.json.
same error in node-fetch before: https://github.com/node-fetch/node-fetch/issues/675]

**Comment by benmccann** [comment] 2021-10-01 17:28
`@rollup/plugin-commonjs` 21.0.0 is out now, so hopefully this should be fixed. I've sent PRs to upgrade SvelteKit https://github.com/sveltejs/kit/pull/2539 and Vite https://github.com/vitejs/vite/pull/5173

**Comment by benmccann** [comment] 2021-10-05 21:31
Vite 2.6.3 and SvelteKit 1.0.0-next.180 have been released and use the fixed version of `@rollup/plugin-commonjs`

**Comment by jimmywarting** [comment] 2021-10-06 00:15
good to hear, dose it work okey now to include fetch-blob?

**Comment by benmccann** [comment] 2021-10-06 00:17
Yes

**Closed** 2021-10-06 00:18 UTC
Labels: bug
